openapi: 3.0.0
info:
  title: Simple Weather API
  description: A simple weather API used to provide weather services to user
  contact:
    email: wangshiyao96@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
- url: https://localhost:8000

security:
- bearerAuth: []
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
- name: users
  description: People using the API with authentications
paths:
  /v1/weather:
    get:
      operationId: v1WeatherGET
      responses:
        "200":
          description: A JSON object as weather information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherItem'
                x-content-type: application/json
        "401":
          description: Access token is missing or invalid
      x-swagger-router-controller: Default
  /v1/hello:
    get:
      operationId: v1HelloGET
      responses:
        "200":
          description: Display a welcome information
          content:
            application/json":
              schema:
                type: string
                example: Hello There!
                x-content-type: application/json"
      x-swagger-router-controller: Default
  /v1/auth:
    post:
      description: Request Authentication from Server
      operationId: v1AuthPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: Authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: "invalid input, object invalid"
        "401":
          description: Invalid username or password
      x-swagger-router-controller: Default
components:
  schemas:
    User:
      required:
      - name
      - password
      type: object
      properties:
        name:
          type: string
          example: John Doe
        password:
          type: string
          example: pass-word-123
    WeatherItem:
      type: object
      properties:
        location:
          type: string
          example: Corvallis
        temp:
          type: integer
          format: int32
          example: 38
        humidity:
          type: integer
          format: int32
          example: 79
      example:
        temp: 38
        humidity: 79
        location: Corvallis
    inline_response_200:
      type: object
      properties:
        token:
          type: string
          example: asOiOPOIUYG123oiuashdIOU2sadiIUTG2413498IUGASiasidhi123OUo897khkKJHklashdilu123IOUASG123123oigoig123oIU3oip1u23NIOUhhaisd987897IUIH
        status:
          type: boolean
      example:
        token: asOiOPOIUYG123oiuashdIOU2sadiIUTG2413498IUGASiasidhi123OUo897khkKJHklashdilu123IOUASG123123oigoig123oIU3oip1u23NIOUhhaisd987897IUIH
        status: true
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
